### ISSUE TITLE
Needs Map

### ISSUE THREAD

**Issue by ScienceDuck** [sketch-city/harvey-p2p#16]
Would be great if people could find and resolve needs more quickly by finding each other on a map and were able to directly reach out to each other. Would need a feedback mechanism so resolved "issues" can be cleared efficiently.

**Comment by laddhoffman** [comment]
There is intersection here with the work underway in slack #harvey-connect project.
We decided to launch with what we have here in order to clarify the use cases we need to address with this tool.
Thanks for the input, it is very welcome.

**Comment by wclifton1** [comment]
going to mark this out of scope for now
