### ISSUE TITLE
phone number formatting

### ISSUE THREAD

**Issue by wclifton1** [sketch-city/harvey-p2p#23]
currently, users are identified by phone number, but formatting of phone number is not uniform on submission. (832) 555-1234 is unique from 832-555-1234 is unique from (832)555-1234 etc

**Comment by laddhoffman** [comment]
Should we store the source number separately from the number the user may provide? One issue is with the SMS dialog, their response to the phone number question can be rather free-form.
Maybe we can add a "preferred number" column to store their response if it is anything other than "YES" (in the relevant language)?
Other than that, it should be no problem to format the source phone number correctly & consistently.

**Comment by wclifton1** [comment]
zendesk and zapier will not break with adding columns. they will break with renaming columns or deleting columns. they SHOULD not break with rearranging columns, but i would try to avoid it. sometimes i see in zapier something like "PHONE" field replaced with "COL$C" field and it makes me nervous.

**Comment by wclifton1** [comment]
i would prefer that if the SMS user provides an alternate number (and no additional text), we are able to format it and place it into the PHONE field. all text from that response can also be stored in additional column

**Comment by wclifton1** [comment]
same formatting rules for that SMS response that we can use for the webform i assume

**Comment by laddhoffman** [comment]
@wclifton1 Ok that sounds good. If extra text is provided I could just append it to the Notes field

**Comment by wclifton1** [comment]
i don't want to lose the original number that sent the SMS, but it seems like we should default to contacting them at (and creating a user based on) the number provided as preferred

**Comment by laddhoffman** [comment]
If they specify a number, the original can also be appended to Notes

**Comment by wclifton1** [comment]
what are you using as the default formatting? i can update the existing tickets. a large majority are in the (832) 555-1234 format

**Comment by laddhoffman** [comment]
I was thinking we'd go with the one most of them currently use, so "(000) 000-0000"

**Comment by wclifton1** [comment]
great

**Comment by laddhoffman** [comment]
What about the leading country code?

**Comment by laddhoffman** [comment]
The web form currently omits it, which implies we assume USA

**Comment by wclifton1** [comment]
i think that is a safe assumption for this iteration. if you receive >10 digits via the sms response, you could just store that in notes / preferred phone unformatted?
